export const dummyProducts = [
  {
    variants: {
      enabled: true,
      useDefaultPricing: true,
      attributes: [
        {
          name: "Size",
          required: false,
          value: [
            {
              name: "Small",
              sku: "SZ-SM",
              price: { $numberDecimal: "0" },
              discountPrice: { $numberDecimal: "0" },
              stock: 50,
              status: true,
              image: [],
              _id: "var1",
            },
            {
              name: "Medium",
              sku: "SZ-MD",
              price: { $numberDecimal: "0" },
              discountPrice: { $numberDecimal: "0" },
              stock: 30,
              status: true,
              image: [],
              _id: "var2",
            },
          ],
          _id: "attr1",
        },
      ],
    },
    _id: "prod001",
    productName: "Wireless Bluetooth Headphones",
    productCategory: "Audio & Sound",
    productSubCategory: "Headphones",
    productBrand: "Sony",
    productDescription: null,
    productShortDescription:
      "Premium noise-cancelling wireless headphones with 30-hour battery life",
    productPrice: 299,
    productCost: 150,
    productDiscount: 50,
    tax: false,
    tags: ["wireless", "bluetooth", "noise-cancelling"],
    thumbnailImage: "",
    productImage: [],
    flash_sale: true,
    rating: 4.5,
    flash_sale_show_countdown: true,
    new_arrival: true,
    best_seller: true,
    best_seller_threshold: 100,
    hot_deal: true,
    limited_stock: false,
    limited_stock_threshold: 0,
    featured: true,
    productQuantity: 80,
    shippingCharges: 0,
    productStatus: true,
    storeId: "6857bc3e4205851792ca088a",
    createdAt: "2025-12-15T10:00:00.000Z",
    __v: 0,
    productId: "prod001",
  },
  {
    variants: {
      enabled: false,
      useDefaultPricing: true,
      attributes: [],
    },
    _id: "prod002",
    productName: "Smart Watch Pro",
    productCategory: "Wearables",
    productSubCategory: "Smart Watches",
    productBrand: "Apple",
    productDescription: null,
    productShortDescription:
      "Advanced fitness tracking with heart rate monitor and GPS",
    productPrice: 449,
    productCost: 220,
    productDiscount: 0,
    tax: false,
    tags: ["fitness", "smartwatch", "gps"],
    thumbnailImage: "",
    productImage: [],
    flash_sale: false,
    rating: 4.8,
    flash_sale_show_countdown: false,
    new_arrival: true,
    best_seller: true,
    best_seller_threshold: 150,
    hot_deal: false,
    limited_stock: false,
    limited_stock_threshold: 0,
    featured: true,
    productQuantity: 45,
    shippingCharges: 0,
    productStatus: true,
    storeId: "6857bc3e4205851792ca088a",
    createdAt: "2025-12-14T09:30:00.000Z",
    __v: 0,
    productId: "prod002",
  },
  {
    variants: {
      enabled: true,
      useDefaultPricing: true,
      attributes: [
        {
          name: "Color",
          required: false,
          value: [
            {
              name: "Black",
              sku: "COL-BLK",
              price: { $numberDecimal: "0" },
              discountPrice: { $numberDecimal: "0" },
              stock: 25,
              status: true,
              image: [],
              _id: "var3",
            },
            {
              name: "White",
              sku: "COL-WHT",
              price: { $numberDecimal: "0" },
              discountPrice: { $numberDecimal: "0" },
              stock: 20,
              status: true,
              image: [],
              _id: "var4",
            },
          ],
          _id: "attr2",
        },
      ],
    },
    _id: "prod003",
    productName: "USB-C Fast Charger",
    productCategory: "Accessories",
    productSubCategory: "Chargers",
    productBrand: "Anker",
    productDescription: null,
    productShortDescription:
      "65W fast charging with multiple ports and compact design",
    productPrice: 49,
    productCost: 20,
    productDiscount: 10,
    tax: false,
    tags: ["charger", "usb-c", "fast-charging"],
    thumbnailImage: "",
    productImage: [],
    flash_sale: true,
    rating: 4.6,
    flash_sale_show_countdown: true,
    new_arrival: false,
    best_seller: true,
    best_seller_threshold: 200,
    hot_deal: true,
    limited_stock: true,
    limited_stock_threshold: 50,
    featured: false,
    productQuantity: 45,
    shippingCharges: 5,
    productStatus: true,
    storeId: "6857bc3e4205851792ca088a",
    createdAt: "2025-12-13T14:20:00.000Z",
    __v: 0,
    productId: "prod003",
  },
  {
    variants: {
      enabled: false,
      useDefaultPricing: true,
      attributes: [],
    },
    _id: "prod004",
    productName: "4K Action Camera",
    productCategory: "Cameras & Photography",
    productSubCategory: "Action Cameras",
    productBrand: "GoPro",
    productDescription: null,
    productShortDescription:
      "Waterproof 4K camera with image stabilization for adventure",
    productPrice: 399,
    productCost: 200,
    productDiscount: 80,
    tax: false,
    tags: ["camera", "4k", "waterproof", "action"],
    thumbnailImage: "",
    productImage: [],
    flash_sale: false,
    rating: 4.7,
    flash_sale_show_countdown: false,
    new_arrival: true,
    best_seller: false,
    best_seller_threshold: 0,
    hot_deal: true,
    limited_stock: false,
    limited_stock_threshold: 0,
    featured: true,
    productQuantity: 30,
    shippingCharges: 0,
    productStatus: true,
    storeId: "6857bc3e4205851792ca088a",
    createdAt: "2025-12-12T11:45:00.000Z",
    __v: 0,
    productId: "prod004",
  },
  {
    variants: {
      enabled: true,
      useDefaultPricing: true,
      attributes: [
        {
          name: "Storage",
          required: true,
          value: [
            {
              name: "128GB",
              sku: "STR-128",
              price: { $numberDecimal: "0" },
              discountPrice: { $numberDecimal: "0" },
              stock: 15,
              status: true,
              image: [],
              _id: "var5",
            },
            {
              name: "256GB",
              sku: "STR-256",
              price: { $numberDecimal: "100" },
              discountPrice: { $numberDecimal: "80" },
              stock: 10,
              status: true,
              image: [],
              _id: "var6",
            },
          ],
          _id: "attr3",
        },
      ],
    },
    _id: "prod005",
    productName: "Smartphone X Pro",
    productCategory: "Mobile Phones",
    productSubCategory: "Smartphones",
    productBrand: "Samsung",
    productDescription: null,
    productShortDescription:
      "Latest flagship with stunning display and professional camera system",
    productPrice: 999,
    productCost: 500,
    productDiscount: 150,
    tax: true,
    tags: ["smartphone", "5g", "flagship"],
    thumbnailImage: "",
    productImage: [],
    flash_sale: true,
    rating: 4.9,
    flash_sale_show_countdown: true,
    new_arrival: true,
    best_seller: true,
    best_seller_threshold: 80,
    hot_deal: true,
    limited_stock: true,
    limited_stock_threshold: 30,
    featured: true,
    productQuantity: 25,
    shippingCharges: 0,
    productStatus: true,
    storeId: "6857bc3e4205851792ca088a",
    createdAt: "2025-12-11T08:15:00.000Z",
    __v: 0,
    productId: "prod005",
  },
  {
    variants: {
      enabled: false,
      useDefaultPricing: true,
      attributes: [],
    },
    _id: "prod006",
    productName: "Portable Bluetooth Speaker",
    productCategory: "Audio & Sound",
    productSubCategory: "Speakers",
    productBrand: "JBL",
    productDescription: null,
    productShortDescription:
      "Waterproof portable speaker with 20-hour playtime and powerful bass",
    productPrice: 129,
    productCost: 60,
    productDiscount: 30,
    tax: false,
    tags: ["speaker", "bluetooth", "waterproof", "portable"],
    thumbnailImage: "",
    productImage: [],
    flash_sale: false,
    rating: 4.4,
    flash_sale_show_countdown: false,
    new_arrival: false,
    best_seller: true,
    best_seller_threshold: 120,
    hot_deal: false,
    limited_stock: false,
    limited_stock_threshold: 0,
    featured: false,
    productQuantity: 65,
    shippingCharges: 0,
    productStatus: true,
    storeId: "6857bc3e4205851792ca088a",
    createdAt: "2025-12-10T16:30:00.000Z",
    __v: 0,
    productId: "prod006",
  },
  {
    variants: {
      enabled: true,
      useDefaultPricing: true,
      attributes: [
        {
          name: "Color",
          required: false,
          value: [
            {
              name: "Silver",
              sku: "COL-SLV",
              price: { $numberDecimal: "0" },
              discountPrice: { $numberDecimal: "0" },
              stock: 12,
              status: true,
              image: [],
              _id: "var7",
            },
            {
              name: "Space Gray",
              sku: "COL-GRY",
              price: { $numberDecimal: "0" },
              discountPrice: { $numberDecimal: "0" },
              stock: 8,
              status: true,
              image: [],
              _id: "var8",
            },
          ],
          _id: "attr4",
        },
      ],
    },
    _id: "prod007",
    productName: "Wireless Keyboard & Mouse Combo",
    productCategory: "Computer Accessories",
    productSubCategory: "Keyboards & Mice",
    productBrand: "Logitech",
    productDescription: null,
    productShortDescription:
      "Ergonomic wireless combo with silent keys and precision tracking",
    productPrice: 79,
    productCost: 35,
    productDiscount: 15,
    tax: false,
    tags: ["keyboard", "mouse", "wireless", "ergonomic"],
    thumbnailImage: "",
    productImage: [],
    flash_sale: false,
    rating: 4.3,
    flash_sale_show_countdown: false,
    new_arrival: false,
    best_seller: false,
    best_seller_threshold: 0,
    hot_deal: false,
    limited_stock: false,
    limited_stock_threshold: 0,
    featured: false,
    productQuantity: 40,
    shippingCharges: 5,
    productStatus: true,
    storeId: "6857bc3e4205851792ca088a",
    createdAt: "2025-12-09T13:00:00.000Z",
    __v: 0,
    productId: "prod007",
  },
  {
    variants: {
      enabled: false,
      useDefaultPricing: true,
      attributes: [],
    },
    _id: "prod008",
    productName: "Smart Home Hub",
    productCategory: "Smart Home",
    productSubCategory: "Home Automation",
    productBrand: "Amazon",
    productDescription: null,
    productShortDescription:
      "Central control for all your smart home devices with voice assistant",
    productPrice: 149,
    productCost: 75,
    productDiscount: 40,
    tax: false,
    tags: ["smart-home", "voice-assistant", "automation"],
    thumbnailImage: "",
    productImage: [],
    flash_sale: true,
    rating: 4.6,
    flash_sale_show_countdown: false,
    new_arrival: true,
    best_seller: false,
    best_seller_threshold: 0,
    hot_deal: true,
    limited_stock: false,
    limited_stock_threshold: 0,
    featured: false,
    productQuantity: 35,
    shippingCharges: 0,
    productStatus: true,
    storeId: "6857bc3e4205851792ca088a",
    createdAt: "2025-12-08T10:45:00.000Z",
    __v: 0,
    productId: "prod008",
  },
];

export const footerLinks = {
  company: [
    { label: "About", url: "/about" },
    { label: "Contact", url: "/contact" },
    { label: "Blog", url: "/blog" },
  ],

  shop: [
    { label: "Shop", url: "/shop" },
    { label: "Best Sellers", url: "/products?filter=bestseller" },
    { label: "New Arrivals", url: "/products?filter=new-arrival" },
    { label: "Sale", url: "/products?filter=sale" },
  ],

  support: [
    { label: "Customer Support", url: "/support/customer-support" },
    { label: "Return Policy", url: "/support/return-policy" },
    { label: "Legal & Terms", url: "/support/terms-and-conditions" },
    { label: "Shopping Guide", url: "/support/shopping-guide" },
  ],
};
